In [1]:
def naive_relu(x):
    assert len(x.shape) == 2


    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j], 0)
    return x

In [3]:
import numpy as np

x=np.array([1,2,3])

In [4]:
x.copy()

array([1, 2, 3])

In [5]:
id(x)

140539148032400

In [7]:
id(x.copy())

140539148278880

In [11]:
id(x)

140539147398000

In [9]:
x=x.copy()

In [12]:
id(x)

140539147398000

In [13]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
    return x

In [14]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[j]
    return x

In [15]:
import numpy as np

x=np.random.random((64,3,32,10))
y=np.random.random((32,10))

z = np.maximum(x,y)

In [18]:
z.shape

(64, 3, 32, 10)

In [20]:
def naive_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]


    z=0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [21]:
import numpy as np
def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    z=np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i,j] * y[j]
    return z

In [22]:
def naive_matrix_vector_dot(x,y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i,:],y)
    return z

In [23]:
def naive_matrix_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]

    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i,:]
            column_y = y[:,j]
            z[i,j] = naive_vector_dot(row_x, column_y)
    return z

In [25]:
x=np.array([[0.,1.],
           [2.,3.],
           [4.,5.]])
print(x.shape)

(3, 2)


In [26]:
x=x.reshape((6,1))

In [27]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [28]:
x=x.reshape((2,3))

In [29]:
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [30]:
x=np.zeros((300,20))

In [31]:
x=np.transpose(x)

In [32]:
print(x.shape)

(20, 300)
